# See: https://gohugo.io/getting-started/configuration/

####### BASE CONFIG #######
  baseURL = "https://im.youronly.one/"                                              # .Site.BaseURL
  title = "I'M YourOnly.One"                                                # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards; RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty to override theme
  timeZone = "Etc/UTC"


####### FRONTEND #######
  paginate = 100                                             # default: 10
  rssLimit = 25                                             # default: -1
  summaryLength = 240                                        # default: 70
  titleCaseStyle = "firstupper"                                     # default: AP; our choice: firstupper; backup: Chicago


####### LANGUAGE #######
  languageCode = "en-ph"
  defaultContentLanguage = "en-ph"                             # default: en
  hasCJKLanguage = true                                    # default: false
  # Our LANG: 'en', 'en-ph', 'fil', 'phi-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko'
  disableLanguages = ['en', 'fil', 'phi-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko']


####### BACKEND #######

  disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
  enableMissingTranslationPlaceholders = true              # default: false
  pluralizeListTitles = false                                # default: true
  timeout = "70s"                                           # default: 30s


#######  #######  #######  #######  #######  #######  #######  #######
