# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  description = "â™¾ï¸ ğŸ¬ I'M YourOnly.One ğŸ” by áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®) / Yahuhanan Yukia Sese Cuneta."
  keywords = ["YourOnly.One", "Yuki", "áœŒáœ“áœƒáœ’"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  message = "<bdi lang='tl-Tglg' class='font-baybayin-noto'>áœ‹áœŠáœ“áœ‘áœŒáœ”áœ¶</bdi> Welcome to my hub. These are my official links/profiles in cyberspace. <bdi lang='hbo-Hebr' class='font-hebrew-sans-noto'>ğ¤”ğ¤‹ğ¤…ğ¤Œ ğ¤ğ¤‹ğ¤‰ğ¤Šğ¤Œ</bdi>"
  hideAutoMenu = false

  # Pagination options
  paginate = 12
  multipage = false

  # Dark mode
  darkMode = true
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    sameas = [
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://hashi.icu/@YourOnlyOne",
      "https://youtube.com/@YourOnlyOneOfcl",
      "https://facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
