#mainSections = ["blog", "posts"]                                             # Hugo default
mainTypes = ["article", "sitepage", "review"]                                                # YourOnly.One

rssfull = true
jquerycdn = false
websubhubs = ["https://pubsubhubbub.appspot.com/", "https://youronlyone.superfeedr.com/", "https://pubsubhubbub.superfeedr.com/", "https://websubhub.com/hub"]

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  description = "â™¾ï¸ ğŸ¬ I'M YourOnly.One ğŸ” by áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®) / Yahuhanan Yukia Sese Cuneta."
  license = "https://im.youronly.one/p/legal-notice/"
  keywords = ["YourOnly.One", "Yuki", "áœŒáœ“áœƒáœ’"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
  #copyright = ""
### END: Structured Data ###

### BGN: Theme Settings ###
  message = "<bdi lang='tl-Tglg' class='font-baybayin-noto'>áœ‹áœŠáœ“áœ‘áœŒáœ”áœ¶</bdi> Welcome to my hub. These are my official links/profiles in cyberspace. <bdi lang='hbo-Hebr' class='font-noto-sans-hebrew'>ğ¤”ğ¤‹ğ¤…ğ¤Œ ğ¤ğ¤‹ğ¤‰ğ¤Šğ¤Œ</bdi>"
  hideAutoMenu = false

  # Pagination options
  paginate = 12
  multipage = false

  # Dark mode
  darkMode = false
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    org = "yelosan"

    #isni = ""
    #issn = ""
    acquirelicensepage = "https://im.youronly.one/p/legal-notice/"
    copyrightnotice = "Copyleft ğŸ„¯ CC-BY-SA 4.0 International by JC John Sese Cuneta"
    credittext = "â™¾ï¸ ğŸ¬ I'M YourOnly.One ğŸ” (https://im.youronly.one/)"
    datecreated = "2021-02-06"
    #isblog = true
    license = "https://im.youronly.one/p/legal-notice/"
    publisher = "https://yelosan.youronly.one/"
    sameas = [
      "https://facebook.com/101597304949708/",
      "https://facebook.com/yelosanpub/",
      "https://codeberg.org/yelosan",
      "https://gitlab.com/yelosan",
      "https://github.com/yelosan"
    ]

    [[semweb.persons]]
      person = "yuki"
      #id = ""
      #name = ""áœŒáœ“áœƒáœ’ (é›ªäº® | ìŠ¤ë…¸ | Yuki)"
      #url = ""
      #avatar = ""
      #rel = "noopener external nofollow"

  [verify]
    flattr = "4j1gl5"
    wot = "06c7ef6e7986586661ef"
    ocs = "c563648adcfa021a0dfd3d3d8f0be64a"
		followit = "jqEnpsdBvHltNryJFB4A"

  [analytics]
    cfwebanalytics = "07a05e5302d1458da3561ce41791e284"
    microanalyticsio = "ZwSg9rf6GA"
    naver = "1375cb4224f1c40"   # https://youronly.one
    #naver = "137a7c92882ac90"   # https://im.youronly.one
    counterdev = "youronlyone"
    swetrix = "bYdcXUajNvru"
    microsoftclarity = "63ddi0b99e"
### END: Other Settings ###
