replacements = [
  "github.com/YourOnly-One/yoo-hugo-defaults -> /home/yuki/repos/hugo-modules/yoo-hugo-defaults",
  "github.com/YourOnly-One/hugo-structured-data -> /home/yuki/repos/hugo-modules/hugo-structured-data",
  "github.com/YourOnly-One/hugo-shortcodes -> /home/yuki/repos/hugo-modules/hugo-shortcodes",
  "github.com/YourOnly-One/hugo-atom-feed -> /home/yuki/repos/hugo-modules/hugo-atom-feed",
  "github.com/techmagus/hugo-theme-showcase -> /home/yuki/repos/hugo-themes/frontpage-hugo-theme-showcase",
  "github.com/YourOnly-One/yoo-hugo-content -> /home/yuki/repos/hugo-modules/yoo-hugo-content"
]

[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "github.com/YourOnly-One/yoo-hugo-defaults"

[[imports]]
  path = "github.com/YourOnly-One/hugo-structured-data"

[[imports]]
  path = "github.com/YourOnly-One/hugo-shortcodes"

[[imports]]
  path = "github.com/YourOnly-One/hugo-atom-feed"

[[imports]]
  path = "github.com/techmagus/hugo-theme-showcase"

[[imports]]
  path = "github.com/YourOnly-One/yoo-hugo-content"
  # BGN: /frontpage/ content
    #[[imports.mounts]]
    #  source = "frontpage/eng-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "frontpage/eng-ph"
      target = "content"
      lang = "en-ph"
    #[[imports.mounts]]
    #  source = "frontpage/nihongo"
    #  target = "content"
    #  lang = "ja"
    #[[imports.mounts]]
    #  source = "frontpage/hangugeo"
    #  target = "content"
    #  lang = "ko"
  # END: /frontpage/ content


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  #[[mounts]]
  #  source = "content/eng-ph"
  #  target = "content"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "content/eng-ph"
    target = "content"
    lang = "en-ph"                                      # when in multihost / multilang mode
  #[[mounts]]
  #  source = "content/nihongo"
  #  target = "content"
  #  lang = "ja"                                         # when in multihost / multilang mode
  #[[mounts]]
  #  source = "content/hangugeo"
  #  target = "content"
  #  lang = "ko"                                         # when in multihost / multilang mode

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  #[[mounts]]
  #  source = "static/eng-ph"
  #  target = "static"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "static/eng-ph"
    target = "static"
    lang = "en-ph"                                      # when in multihost / multilang mode
  #[[mounts]]
  #  source = "static/nihongo"
  #  target = "static"
  #  lang = "ja"                                         # when in multihost / multilang mode
  #[[mounts]]
  #  source = "static/hangugeo"
  #  target = "static"
  #  lang = "ko"                                         # when in multihost / multilang mode
